(defun chop (splitter str)
  (let ((before (search splitter str)))
    (unless (EQL before nil)
      (let ((after (+ before (length splitter))))
        (list (subseq str 0 before) 
          (subseq str after (length str)))))))